default_environment: default
environments:
    default:
        connections:
            duckdb:
                - name: duckdb-default
                  path: /workspaces/DE-Zoomcamp-ShriHari/bruin-zoomcamp/taxi.db
