id: taxi_data_etl
namespace: zoomcamp

inputs:
  - id: taxi
    type: SELECT
    values: ["green", "yellow", "fhv"]
    defaults: "yellow"
  - id: year
    type: STRING
    defaults: "2024"
  - id: month
    type: STRING
    defaults: "01"

variables:
  bucket_name: "celtic-vent-487722-f0-terra-bucket"
  project_id: "celtic-vent-487722-f0"

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: "https://d37ci6vzurychx.cloudfront.net/trip-data/{{inputs.taxi}}_tripdata_{{trigger.date is defined ? trigger.date | date('yyyy') : inputs.year}}-{{trigger.date is defined ? trigger.date | date('MM') : inputs.month}}.parquet"

  - id: upload_to_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{ outputs.extract.uri }}"
    to: "gs://{{ vars.bucket_name }}/{{inputs.taxi}}/{{trigger.date is defined ? trigger.date | date('yyyy') : inputs.year}}/{{inputs.taxi}}_tripdata_{{trigger.date is defined ? trigger.date | date('yyyy') : inputs.year}}-{{trigger.date is defined ? trigger.date | date('MM') : inputs.month}}.parquet"
    serviceAccount: "{{ secret('GCP_CREDS') }}"
    projectId: "{{ vars.project_id }}"

  - id: create_external_table
    type: io.kestra.plugin.gcp.bigquery.Query
    serviceAccount: "{{ secret('GCP_CREDS') }}"
    projectId: "{{ vars.project_id }}"
    sql: |
      CREATE OR REPLACE EXTERNAL TABLE `{{ vars.project_id }}.trips_data_all.{{inputs.taxi}}_tripdata_{{trigger.date is defined ? trigger.date | date('yyyy') : inputs.year}}`
      OPTIONS (
        format = 'PARQUET',
        uris = ['gs://{{ vars.bucket_name }}/{{inputs.taxi}}/{{trigger.date is defined ? trigger.date | date('yyyy') : inputs.year}}/*.parquet']
      );

triggers:
  - id: monthly
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 1 * *"